/* eslint-disable */

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZoneZoneIdRouteImport } from './routes/zone.$zoneId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})

const ZoneZoneIdRoute = ZoneZoneIdRouteImport.update({
  id: '/zone/$zoneId',
  path: '/zone/$zoneId',
  getParentRoute: () => rootRouteImport,
})

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  ZoneZoneIdRoute: ZoneZoneIdRoute,
}

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
